# Generated by Django 6.0.4 on 2026-04-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cardlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='card',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='tags',
        ),
    ]
