# Generated by Django 6.0.4 on 2026-05-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador (Dono)'), ('MANAGER', 'Gerente de Projeto'), ('MEMBER', 'Membro da Equipe')], default='ADMIN', max_length=20),
        ),
    ]
