# Generated by Django 6.0.4 on 2026-05-13 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='theme_hex',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='wallpapers/'),
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador (Dono)'), ('MANAGER', 'Gerente de Projeto'), ('MEMBER', 'Membro da Equipe')], default='MEMBER', max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='api.company')),
            ],
        ),
    ]
