# Generated by Django 6.0.4 on 2026-05-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_company_theme_hex_company_wallpaper_teaminvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_users',
            field=models.IntegerField(default=2),
        ),
    ]
