# Generated by Django 6.0.4 on 2026-06-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_checklistitem_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
