# Generated by Django 6.0.4 on 2026-09-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_card_completed_at_card_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('contabil', 'Contabilidade'), ('vistos', 'Assessoria de Vistos'), ('tech', 'Tecnologia'), ('juridico', 'Juridico'), ('consultoria', 'Consultoria'), ('outro', 'Outro')], default='outro', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_all_cards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_financials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.CharField(choices=[('geral', 'Geral'), ('fiscal', 'Fiscal'), ('pessoal', 'Departamento Pessoal'), ('contabil', 'Contabil'), ('financeiro', 'Financeiro'), ('ti', 'Tecnologia'), ('comercial', 'Comercial'), ('juridico', 'Juridico'), ('administrativo', 'Administrativo')], default='geral', max_length=30),
        ),
    ]
