# Generated by Django 6.0.4 on 2026-09-16 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_company_company_type_user_can_manage_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='blocked_by',
            field=models.CharField(blank=True, default='', help_text='Quem esta segurando a entrega. Vazio = nao bloqueado.', max_length=120),
        ),
        migrations.AddField(
            model_name='card',
            name='blocked_since',
            field=models.DateField(blank=True, help_text='Preenchido automaticamente quando blocked_by passa a ter valor.', null=True),
        ),
        migrations.CreateModel(
            name='Frente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='#67737E', help_text='Hex com #, ex: #1F5FA8', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frentes', to='api.board')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='frente',
            field=models.ForeignKey(blank=True, help_text="Frente de trabalho. Nulo cai em 'Sem frente' no Painel.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='api.frente'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['stage', 'due_date'], name='api_card_stage_i_522b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['stage', 'is_completed'], name='api_card_stage_i_c117a1_idx'),
        ),
        migrations.AddIndex(
            model_name='frente',
            index=models.Index(fields=['board', 'order'], name='api_frente_board_i_a8b6f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='frente',
            unique_together={('board', 'name')},
        ),
    ]
